<?php
return  array(
	'db'=>[
		'db1'=>[
			'host'=>'127.0.0.1',
			'username'=>'root',
			'password'=>'root',
			'dbname'=>'eleven',
			'tbPrefix'=>'',
			'pConnect'=>0,
		],
		'db2'=>[
			'host'=>'127.0.0.1',
			'username'=>'root',
			'password'=>'root',
			'dbname'=>'eleven',
			'tbPrefix'=>'',
			'pConnect'=>0,
		]
	]
);